### ISSUE TITLE
Unlocking Floor 41 to 99

### ISSUE THREAD

**Issue by SandKnight** [ProGrammar-R/ProGrammar-R.github.io#16]
Opening Floor 41 to 99

-probably turn floor 40 as a normal generated floor.
-make floor 99 the actual end of the game with the beldo cutscene and the ultimate egg
-Make monster same level as the floor they appear on
-make it compatible with the enemizer mod.

**Comment by ProGrammar-R** [comment]
@SandKnight Added in v1.6.0-beta. As stated elsewhere, I have made monsters their normal level +40/80 for the set of floors starting with 41/81, respectively. This avoids complexity of needing two different ways of handling level scaling.
