### ISSUE TITLE
Petomizer Additions

### ISSUE THREAD

**Issue by BaldwinGG** [ProGrammar-R/ProGrammar-R.github.io#18]
I really like the Petomizer option, but I've thought about a few improvements that would greatly add to the randomization of the starting familiar and create a unique experience by utilizing the wasted potential of familiars due the limiting game mechanic where familiars cannot level up spells when they are out of their native genus. There are many unique spell animations in the game that simply are never seen because there is generally no point to changing the element of your familiar (outside of a few instances), and because changing familiars out of their native genus means that their spells can no longer level up. What this means is that usually only fire mixture magic is seen or is useful.

I propose the following:

- A randomize element option (meaning that the starting familiar would also be of a random element)

- Allow spells outside of their native genus to level up

- Dormant spells being unlocked naturally instead of being fused (a suggestion from Sandknight, edited this in)

These options would greatly increase the randomness of the starting familiar option and allow the practically unseen spell animations to have use and be seen in gameplay, allowing for even more unique options and experiences to people playing.

**Comment by ProGrammar-R** [comment]
@BaldwinGG I like the suggestions and have started work on the second of these. Since these are likely to be worked on one-by-one and implemented as individual options, would you please create three new separate issues, one for each? That way, we can keep track of them better.

**Comment by BaldwinGG** [comment]
Awesome! Absolutely, I'll do that now.

**Comment by ProGrammar-R** [comment]
Thanks for breaking these down, I've already knocked one out. For posterity, these are #19, #20, #21. When all three are done, I'll close this issue.
