### ISSUE TITLE
Off-Genus Leveling

### ISSUE THREAD

**Issue by BaldwinGG** [ProGrammar-R/ProGrammar-R.github.io#20]
An option that allows spells outside of their native element to level up as they would normally.

**Comment by ProGrammar-R** [comment]
@BaldwinGG Thank you for making this a separate issue. I have implemented this in v1.4.1, which is live now (version number might say 1.4.0 for a few more minutes).

**Comment by ProGrammar-R** [comment]
@BaldwinGG One more thing I forgot to add: I implemented this in the strictest sense; that is, only off-genus leveling is affected. It is possible to modify all spells so that each spell's native element is the spell's actual element, but this might have other effects, so I left those as they were.
