### ISSUE TITLE
Randomize items on floor 1

### ISSUE THREAD

**Issue by SandKnight** [ProGrammar-R/ProGrammar-R.github.io#30]
Rando items on tutorial floor, but keeping 1 weapon 1 shield a ball an egg (leaving medicinal herb intact) and make it so item are un-tempered uncursed and identified, ball is 5 charge (acid rain is still 1 charge) equal chance of all items in category and no curse on dark sword.

**Comment by ProGrammar-R** [comment]
@SandKnight Essentially done as of v1.5.0. For technical reasons related to how eggs are identified, the egg will not be identified. As of now, I'm considering that a won't fix item. See changelog for more notes.
