### ISSUE TITLE
20 Items only Challenge

### ISSUE THREAD

**Issue by SandKnight** [ProGrammar-R/ProGrammar-R.github.io#48]
you start on floor 1 with a good choice of items but then no items spawn past floor 1

**Comment by ProGrammar-R** [comment]
@SandKnight I'm not sure how many items I can put on the floor, but here's what I'm thinking of including. Feel free to suggest changes to this list:
All 3 elemental wands
Life wand
Seraphim sword

All 3 elemental shields
Mirror shield
Diamond shield

1 each ball, 5 charges (1 charge for Acid Rain)

1 Roche fruit (but no egg on floor 1)

2 of each of the following:
Holy bell
Familiar bell
Holy scroll
Malicious scroll
Oleem fruit
Tumna fruit
Star glasses
Big Pita fruit
Medicinal herb
Cure-all herb

**Comment by SandKnight** [comment]
that is a really good list. i'd have chosen the same ^^
